### ISSUE TITLE
Is there a Drobo FS version?

### ISSUE THREAD

**Issue by nojkepop** [droboports/owncloud#1]
It states there should be another branch but I am not seeing one.

**Comment by ricardopadilha** [comment]
OwnCloud requires MySQL, which is just too big for the Drobo FS. The FS simply does not have enough RAM to run Apache + MySQL + OwnCloud. Even if you increased swap space it would be a miserable experience.

Other than that, OwnCloud itself is just a PHP app, so you could conceivably try to run it by just copying the OwnCloud files in a folder under DroboApps/apache/www/
