### ISSUE TITLE
Upgrades?

### ISSUE THREAD

**Issue by joelschou** [droboports/owncloud#2]
Is there any chance you'll be updating this port to newer versions of ownCloud? I was hoping the built-in upgrade mechanism work work, but I get this error every time:

>Update failed.Unable to move /mnt/DroboFS/Shares/DroboApps/owncloud/app/_oc-upgrade/8.2.11/core/resources to /mnt/DroboFS/Shares/DroboApps/owncloud/app/resources

I haven't yet poked around to see if there's anything obvious causing this to go wrong. If'n'when I do, I'll come back with more info. Thanks!

**Comment by ricardopadilha** [comment]
I recommend using DroboAccess instead. It is also based on ownCloud, and it is a more recent version.

**Comment by joelschou** [comment]
I noticed the UI similarities, but for whatever reason DroboAccess is quite a bit slower than ownCloud. I can deal with it. Thanks!
